### ISSUE TITLE
Build fails on some platforms

### ISSUE THREAD

**Issue by andy5995** [netpanzer/flexlay#1]
https://github.com/netpanzer/flexlay/actions/runs/7722713281/job/21051346285#step:6:116

>lib/gui_manager.cpp: In constructor ‘GUIManager::GUIManager()’:
lib/gui_manager.cpp:42:75: error: no matching function for call to ‘CL_ResourceManager::CL_ResourceManager(std::__cxx11::basic_string<char>, bool)’
   42 |   impl->resources = new CL_ResourceManager(datadir + "/gui/gui.xml", false);

**Comment by andy5995** [comment]
The build now works on Ubuntu 22.04 but fails on Manjaro:

```
[andy@prometheus flexlay](main)$ scons
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
g++ -o ruby/ruby_meta_data.os -c -Wno-uninitialized -I/usr/include/ruby-3.0.0 -I/usr/include/ruby-3.0.0/x86_64-linux -fPIC -Iruby -I/usr/lib/ruby/3.0.0/x86_64-linux -Ilib -I/usr/include/ClanLib-1.0 ruby/ruby_meta_data.cpp
In file included from /usr/include/ruby-3.0.0/ruby/ruby.h:144,
                 from /usr/include/ruby-3.0.0/ruby.h:38,
                 from ruby/ruby_meta_data.hpp:24,
                 from ruby/ruby_meta_data.cpp:19:
/usr/include/boost/assert/source_location.hpp: In member function ‘std::string boost::source_location::to_string() const’:
/usr/include/ruby-3.0.0/ruby/subst.h:14:18: error: ‘ruby_snprintf’ is not a member of ‘std’; did you mean ‘vsnprintf’?
   14 | #define snprintf ruby_snprintf
      |                  ^~~~~~~~~~~~~
/usr/include/ruby-3.0.0/ruby/subst.h:14:18: error: ‘ruby_snprintf’ is not a member of ‘std’; did you mean ‘vsnprintf’?
   14 | #define snprintf ruby_snprintf
      |                  ^~~~~~~~~~~~~
scons: *** [ruby/ruby_meta_data.os] Error 1
scons: building terminated because of errors.
```

**Comment by andy5995** [comment]
Closed via 48707169d0d33ce1aeb669912b0d8e2adc1dc09e
